using Microsoft.JSInterop;

namespace PingMe.Frontend.Services;

public class LocalizationService
{
    private const string StorageKey = "pingme.lang";
    private readonly IJSRuntime _js;
    private bool _loaded;

    public LocalizationService(IJSRuntime js)
    {
        _js = js;
    }

    public string CurrentLanguage { get; private set; } = "vi";

    public event Action? OnLanguageChanged;

    public async Task LoadAsync()
    {
        if (_loaded)
            return;

        try
        {
            var saved = await _js.InvokeAsync<string?>("localStorage.getItem", StorageKey);
            CurrentLanguage = NormalizeLanguage(saved);
        }
        catch
        {
            CurrentLanguage = "vi";
        }

        _loaded = true;
    }

    public async Task SetLanguageAsync(string? lang)
    {
        await LoadAsync();

        var normalized = NormalizeLanguage(lang);
        if (normalized == CurrentLanguage)
            return;

        CurrentLanguage = normalized;

        try
        {
            await _js.InvokeVoidAsync("localStorage.setItem", StorageKey, CurrentLanguage);
        }
        catch
        {
        }

        OnLanguageChanged?.Invoke();
    }

    public Task ToggleLanguageAsync()
        => SetLanguageAsync(CurrentLanguage == "vi" ? "en" : "vi");

    public string T(string key)
    {
        if (string.IsNullOrWhiteSpace(key))
            return string.Empty;

        if (Texts.TryGetValue(CurrentLanguage, out var current) &&
            current.TryGetValue(key, out var value))
        {
            return value;
        }

        if (Texts["vi"].TryGetValue(key, out var fallback))
            return fallback;

        return key;
    }

    private static string NormalizeLanguage(string? lang)
        => string.Equals(lang, "en", StringComparison.OrdinalIgnoreCase) ? "en" : "vi";

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Texts =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            ["vi"] = new Dictionary<string, string>
            {
                ["nav.messages"] = "Tin nhắn",
                ["nav.groups"] = "Nhóm",
                ["nav.search"] = "Tìm kiếm",
                ["nav.saved"] = "Đã lưu",
                ["nav.friends"] = "Bạn bè",
                ["nav.code"] = "Code",
                ["nav.ioc"] = "IOC",
                ["nav.pentest"] = "Pentest",
                ["nav.timeline"] = "Dòng thời gian",
                ["nav.tasks"] = "Công việc",
                ["nav.secrets"] = "Secret",
                ["nav.blocked"] = "Đã chặn",
                ["nav.sessions"] = "Phiên",
                ["nav.settings"] = "Cài đặt",

                ["account.profile"] = "Hồ sơ",
                ["account.logout"] = "Đăng xuất",
                ["account.language"] = "Ngôn ngữ",
                ["account.vietnamese"] = "Tiếng Việt",
                ["account.english"] = "English",
                ["account.switchToEnglish"] = "Switch to English",
                ["account.switchToVietnamese"] = "Chuyển sang Tiếng Việt",

                ["saved.title"] = "Tin nhắn đã lưu",
                ["saved.subtitle"] = "Bookmark các tin quan trọng để mở lại nhanh.",
                ["saved.all"] = "Tất cả",
                ["saved.dm"] = "DM",
                ["saved.group"] = "Nhóm",
                ["saved.empty"] = "Chưa có tin nhắn đã lưu",
                ["saved.openOriginal"] = "Mở tin gốc",
                ["saved.unsave"] = "Bỏ lưu",
                ["saved.messageTime"] = "Tin nhắn",
                ["saved.savedAt"] = "Đã lưu",
                ["saved.removed"] = "Đã bỏ lưu tin nhắn.",
                ["saved.removeFailed"] = "Không thể bỏ lưu tin nhắn.",

                ["message.save"] = "Lưu tin nhắn",
                ["message.unsave"] = "Bỏ lưu",
                ["message.saved"] = "Đã lưu tin nhắn.",
                ["message.unsaved"] = "Đã bỏ lưu tin nhắn.",
                ["message.saveFailed"] = "Không thể cập nhật trạng thái lưu tin nhắn.",

                ["time.today"] = "Hôm nay",
                ["time.yesterday"] = "Hôm qua",
                ["time.justNow"] = "Vừa xong",

                ["chat.emptyTitle"] = "Chọn một cuộc trò chuyện",
                ["chat.emptySubtitle"] = "Chọn từ danh sách bên trái hoặc bắt đầu cuộc trò chuyện mới",
                ["chat.messagesTitle"] = "Tin nhắn",
                ["chat.searchPlaceholder"] = "Tìm kiếm...",
                ["chat.inputPlaceholder"] = "Nhập tin nhắn... Gõ / để xem lệnh, @ để tag thành viên",
                ["chat.groupLabel"] = "Nhóm",

                ["reminder.title"] = "Nhắc việc",
                ["reminder.created"] = "Đã tạo nhắc việc",
                ["reminder.syntax"] = "Cú pháp: /reminder 10m nội dung nhắc",
                ["reminder.pending"] = "Đang chờ",
                ["reminder.sent"] = "Đã nhắc",
                ["reminder.completed"] = "Hoàn thành",
                ["reminder.cancelled"] = "Đã hủy",
                ["reminder.dueAt"] = "Nhắc lúc",
                ["reminder.fromCommand"] = "Tạo từ lệnh /reminder",

                ["search.title"] = "Tìm kiếm",
                ["search.subtitle"] = "Tìm trong tin nhắn, người dùng, nhóm, snippet, IOC, finding, task và file.",
                ["search.placeholder"] = "Nhập từ khóa cần tìm...",
                ["search.typeAll"] = "Tất cả",
                ["search.typeMessage"] = "Tin nhắn",
                ["search.typeUser"] = "Người dùng",
                ["search.typeGroup"] = "Nhóm",
                ["search.typeSnippet"] = "Snippet",
                ["search.typeIoc"] = "IOC",
                ["search.typeAttachment"] = "Tệp",
                ["search.typeFinding"] = "Finding",
                ["search.typeTask"] = "Task",
                ["search.fromDate"] = "Từ ngày",
                ["search.toDate"] = "Đến ngày",
                ["search.sender"] = "Người gửi",
                ["search.group"] = "Nhóm",
                ["search.directChatUser"] = "Người chat riêng",
                ["search.allSenders"] = "Tất cả người gửi",
                ["search.allGroups"] = "Tất cả nhóm",
                ["search.allDirectChats"] = "Tất cả cuộc trò chuyện riêng",
                ["search.severity"] = "Mức độ",
                ["search.allSeverities"] = "Tất cả mức độ",
                ["search.noResults"] = "Không tìm thấy kết quả",
                ["search.open"] = "Mở",
                ["search.openMessage"] = "Mở tin nhắn",
                ["search.openFile"] = "Mở tệp",
                ["search.clearFilters"] = "Xóa bộ lọc",
                ["search.searching"] = "Đang tìm kiếm...",
                ["search.loadMore"] = "Tải thêm",
                ["search.dmWith"] = "Tin nhắn riêng với {0}",
                ["search.groupContext"] = "Nhóm: {0}",
                ["search.senderContext"] = "Người gửi: {0}",
                ["search.messageId"] = "Tin nhắn #{0}",

                ["pentest.trackerTitle"] = "Pentest Finding Tracker",
                ["pentest.findingTracker"] = "Pentest Finding Tracker",
                ["pentest.trackerSubtitle"] = "Quản lý lỗ hổng theo group, endpoint, payload và trạng thái xử lý.",
                ["pentest.totalFindings"] = "Tổng finding",
                ["pentest.criticalHigh"] = "Critical/High",
                ["pentest.openFindings"] = "Đang mở",
                ["pentest.closedMitigated"] = "Đã xử lý/đóng",
                ["pentest.findingDetail"] = "Chi tiết finding",
                ["pentest.newFinding"] = "Finding mới",
                ["pentest.editFinding"] = "Sửa finding",
                ["pentest.affectedTarget"] = "Target ảnh hưởng",
                ["pentest.affectedEndpoint"] = "Endpoint ảnh hưởng",
                ["pentest.httpMethod"] = "HTTP method",
                ["pentest.payload"] = "Payload",
                ["pentest.technicalProof"] = "Bằng chứng kỹ thuật",
                ["pentest.overview"] = "Tổng quan",
                ["pentest.fix"] = "Khắc phục",
                ["pentest.noContent"] = "Chưa có nội dung",
                ["pentest.openInTracker"] = "Mở trong Finding Tracker",
                ["pentest.createdFromVuln"] = "Tạo từ lệnh /vuln",
                ["pentest.createdSuccess"] = "Đã tạo finding.",
                ["pentest.updatedSuccess"] = "Đã cập nhật finding.",
                ["pentest.deletedSuccess"] = "Đã xóa finding.",
                ["pentest.vulnCreatedSuccess"] = "Đã tạo Finding từ /vuln",

                ["secrets.title"] = "Secret dùng một lần",
                ["secrets.subtitle"] = "Chia sẻ password, API key hoặc ghi chú nhạy cảm bằng link chỉ mở được một lần.",
                ["secrets.refresh"] = "Làm mới",
                ["secrets.createTitle"] = "Tạo secret",
                ["secrets.secretLabel"] = "Secret",
                ["secrets.expiresLabel"] = "Hết hạn",
                ["secrets.expires5m"] = "5 phút",
                ["secrets.expires1h"] = "1 giờ",
                ["secrets.expires1d"] = "1 ngày",
                ["secrets.createButton"] = "Tạo secret",
                ["secrets.createdList"] = "Secret đã tạo",
                ["secrets.createdAt"] = "Tạo lúc",
                ["secrets.expiresAt"] = "Hết hạn",
                ["secrets.viewedAt"] = "Đã xem",
                ["secrets.status"] = "Trạng thái",
                ["secrets.viewer"] = "Người xem",
                ["secrets.revoke"] = "Thu hồi",
                ["secrets.empty"] = "Chưa có secret nào.",
                ["secrets.shareOnce"] = "Link chỉ hiển thị một lần. Hãy copy ngay.",
                ["secrets.shareLink"] = "Link chia sẻ",
                ["secrets.copyLink"] = "Sao chép link",
                ["secrets.created"] = "Đã tạo secret",
                ["secrets.createFailed"] = "Không thể tạo secret",
                ["secrets.copyDone"] = "Đã copy link",
                ["secrets.revokeDone"] = "Đã thu hồi secret",
                ["secrets.revokeFailed"] = "Không thể thu hồi secret",
                ["secrets.externalViewer"] = "Người mở bên ngoài",
                ["secrets.statusActive"] = "Đang hoạt động",
                ["secrets.statusViewed"] = "Đã xem",
                ["secrets.statusExpired"] = "Hết hạn",
                ["secrets.statusRevoked"] = "Đã thu hồi",

                ["openSecret.title"] = "Secret dùng một lần",
                ["openSecret.openedNotice"] = "Secret đã được mở. Link này sẽ không xem lại được.",
                ["openSecret.copySecret"] = "Sao chép secret",
                ["openSecret.warning"] = "Secret chỉ hiển thị một lần. Chỉ bấm mở khi bạn đã sẵn sàng lưu nội dung.",
                ["openSecret.openButton"] = "Mở secret",
                ["openSecret.expiredOrViewed"] = "Secret đã hết hạn hoặc đã được xem",
                ["friends.title"] = "Bạn bè",
                ["friends.searchPlaceholder"] = "Nhập tên, username, email...",
                ["friends.noResults"] = "Không tìm thấy người dùng nào khớp với \"{0}\".",
                ["friends.sendRequest"] = "Gửi lời mời kết bạn",
                ["friends.tabFriends"] = "Bạn bè",
                ["friends.tabReceived"] = "Lời mời nhận",
                ["friends.tabSent"] = "Lời mời gửi",
                ["friends.noFriends"] = "Chưa có bạn bè nào.",
                ["friends.message"] = "Nhắn tin",
                ["friends.remove"] = "Xóa bạn",
                ["friends.noReceived"] = "Không có lời mời nào.",
                ["friends.sender"] = "Người gửi",
                ["friends.time"] = "Thời gian",
                ["friends.noSent"] = "Chưa gửi lời mời nào.",
                ["friends.receiver"] = "Người nhận",
                ["friends.searchNew"] = "Tìm bạn mới",
                ["snippets.title"] = "Code Snippets",
                ["snippets.subtitle"] = "Lưu, tìm kiếm và chia sẻ các đoạn code dùng trong nội bộ.",
                ["snippets.createBtn"] = "Tạo snippet mới",
                ["snippets.searchPlaceholder"] = "Tìm theo tiêu đề, nội dung hoặc ngôn ngữ...",
                ["snippets.allLanguages"] = "Tất cả ngôn ngữ",
                ["snippets.empty"] = "Bạn chưa có snippet nào. Hãy tạo snippet đầu tiên để lưu các đoạn code thường dùng.",
                ["snippets.noFilterResults"] = "Không tìm thấy snippet phù hợp với bộ lọc hiện tại.",
                ["snippets.noTitle"] = "Không có tiêu đề",
                ["snippets.revoked"] = "Đã thu hồi",
                ["snippets.expired"] = "Hết hạn",
                ["snippets.noExpiry"] = "Không hết hạn",
                ["snippets.views"] = "{0} lượt xem",
                ["snippets.copyLink"] = "Copy link chia sẻ",
                ["snippets.copyCode"] = "Copy code",
                ["snippets.edit"] = "Chỉnh sửa snippet",
                ["snippets.viewFull"] = "Xem đầy đủ",
                ["snippets.fullscreen"] = "Toàn màn hình",
                ["snippets.restoreLink"] = "Khôi phục link chia sẻ",
                ["snippets.revokeLink"] = "Thu hồi link chia sẻ",
                ["snippets.delete"] = "Xóa snippet",
                ["snippets.createTitleModal"] = "Tạo Code Snippet mới",
                ["snippets.createSubtitleModal"] = "Lưu snippet vào kho code nội bộ của bạn.",
                ["snippets.titleLabel"] = "Tiêu đề (tùy chọn)",
                ["snippets.titleHelper"] = "Nếu bỏ trống, hệ thống sẽ tự tạo tiêu đề.",
                ["snippets.languageLabel"] = "Ngôn ngữ",
                ["snippets.codeLabel"] = "Code *",
                ["snippets.codeHelper"] = "Có thể dán raw code hoặc code block dạng ```python ... ```, hệ thống sẽ tự làm sạch.",
                ["snippets.expiryLabel"] = "Thời hạn link chia sẻ",
                ["snippets.cancel"] = "Hủy",
                ["snippets.create"] = "Tạo",
                ["snippets.editTitleModal"] = "Chỉnh sửa Code Snippet",
                ["snippets.editSubtitleModal"] = "Sửa tiêu đề, ngôn ngữ và nội dung code. Link chia sẻ hiện tại vẫn được giữ nguyên.",
                ["snippets.saveChanges"] = "Lưu thay đổi",
                ["snippets.close"] = "Đóng",
                ["ioc.title"] = "IOC Center",
                ["ioc.subtitle"] = "Lưu trữ, tìm kiếm và chia sẻ các Indicators of Compromise.",
                ["ioc.searchPlaceholder"] = "Tìm theo giá trị hoặc ghi chú...",
                ["ioc.addIoc"] = "Thêm IOC",
                ["ioc.type"] = "Loại",
                ["ioc.allTypes"] = "Tất cả loại",
                ["ioc.severity"] = "Mức độ",
                ["ioc.allSeverities"] = "Tất cả mức độ",
                ["ioc.empty"] = "Bạn chưa lưu IOC nào.",
                ["ioc.noFilterResults"] = "Không tìm thấy IOC phù hợp.",
                ["ioc.value"] = "Giá trị",
                ["ioc.note"] = "Ghi chú",
                ["ioc.createdAt"] = "Ngày tạo",
                ["ioc.actions"] = "Thao tác",
                ["ioc.edit"] = "Sửa IOC",
                ["ioc.delete"] = "Xóa IOC",
                ["ioc.cancel"] = "Hủy",
                ["ioc.save"] = "Lưu",
                ["ioc.group"] = "Nhóm",
                ["ioc.severityLow"] = "Thấp",
                ["ioc.severityMedium"] = "Trung bình",
                ["ioc.severityHigh"] = "Cao",
                ["ioc.severityCritical"] = "Nghiêm trọng",
                ["pentest.title"] = "Pentest",
                ["timeline.title"] = "Threat Timeline",
                ["timeline.subtitle"] = "Theo dõi và phân tích chuỗi sự kiện bảo mật theo thời gian thực.",
                ["timeline.addEvent"] = "Thêm sự kiện",
                ["timeline.empty"] = "Chưa có sự kiện nào. Hãy thêm sự kiện đầu tiên.",
                ["timeline.eventTitle"] = "Tiêu đề sự kiện",
                ["timeline.eventTime"] = "Thời gian",
                ["timeline.eventDescription"] = "Mô tả / Chi tiết",
                ["timeline.cancel"] = "Hủy",
                ["timeline.save"] = "Lưu",
                ["timeline.delete"] = "Xóa sự kiện",
                ["timeline.edit"] = "Sửa sự kiện",
                ["timeline.searchPlaceholder"] = "Tìm kiếm sự kiện...",
                ["task.title"] = "Công việc",
                ["task.subtitle"] = "Quản lý công việc và theo dõi tiến độ.",
                ["task.addTask"] = "Thêm Task",
                ["task.empty"] = "Chưa có task nào.",
                ["task.todo"] = "Cần làm",
                ["task.inProgress"] = "Đang làm",
                ["task.done"] = "Hoàn thành",
                ["task.taskName"] = "Tên task",
                ["task.assignee"] = "Người thực hiện",
                ["task.dueDate"] = "Hạn chót",
                ["task.priority"] = "Ưu tiên",
                ["task.save"] = "Lưu task",
                ["task.cancel"] = "Hủy",
                ["task.edit"] = "Sửa task",
                ["task.delete"] = "Xóa task",
                ["blocked.title"] = "Người dùng đã chặn",
                ["blocked.subtitle"] = "Quản lý danh sách những người dùng bạn đã chặn.",
                ["blocked.empty"] = "Bạn chưa chặn ai.",
                ["blocked.unblock"] = "Bỏ chặn",
                ["blocked.name"] = "Tên người dùng",
                ["blocked.blockedAt"] = "Thời gian chặn",
                ["sessions.title"] = "Phiên hoạt động",
                ["sessions.subtitle"] = "Quản lý các thiết bị đang đăng nhập vào tài khoản của bạn.",
                ["sessions.current"] = "Phiên hiện tại",
                ["sessions.revoke"] = "Đăng xuất",
                ["sessions.revokeAll"] = "Đăng xuất tất cả phiên khác",
                ["sessions.browser"] = "Trình duyệt",
                ["sessions.ip"] = "IP",
                ["sessions.lastAccess"] = "Truy cập cuối",
                ["sessions.os"] = "Hệ điều hành",
                ["pentest.cancel"] = "Hủy",
                ["pentest.close"] = "Đóng",
                ["pentest.create"] = "Tạo",
                ["pentest.created"] = "Đã tạo",
                ["pentest.delete"] = "Xóa",
                ["pentest.description"] = "Mô tả",
                ["pentest.detailEmpty"] = "Chưa có chi tiết",
                ["pentest.detailTitle"] = "Chi tiết finding",
                ["pentest.edit"] = "Sửa",
                ["pentest.empty"] = "Không có finding nào.",
                ["pentest.endpoint"] = "Endpoint",
                ["pentest.filter"] = "Lọc",
                ["pentest.findings"] = "Findings",
                ["pentest.fix"] = "Khắc phục",
                ["pentest.group"] = "Nhóm",
                ["pentest.groupId"] = "ID Nhóm",
                ["pentest.loading"] = "Đang tải...",
                ["pentest.loadMore"] = "Tải thêm",
                ["pentest.method"] = "Phương thức",
                ["pentest.open"] = "Đang mở",
                ["pentest.openGroup"] = "Mở nhóm",
                ["pentest.overview"] = "Tổng quan",
                ["pentest.payload"] = "Payload",
                ["pentest.poc"] = "PoC",
                ["pentest.proof"] = "Bằng chứng",
                ["pentest.refresh"] = "Làm mới",
                ["pentest.remediation"] = "Khắc phục",
                ["pentest.results"] = "kết quả",
                ["pentest.save"] = "Lưu",
                ["pentest.search"] = "Tìm kiếm...",
                ["pentest.severity"] = "Mức độ",
                ["pentest.status"] = "Trạng thái",
                ["pentest.subtitle"] = "Quản lý lỗ hổng theo group, endpoint, payload và trạng thái xử lý.",
                ["pentest.target"] = "Mục tiêu",
                ["pentest.titleField"] = "Tiêu đề",
                ["pentest.total"] = "Tổng số",
                ["pentest.updated"] = "Đã cập nhật",
                ["pentest.view"] = "Xem",
                ["timeline.all"] = "Tất cả",
                ["timeline.download"] = "Tải xuống",
                ["timeline.emptyDesc"] = "Hiện chưa có hoạt động nào được ghi nhận.",
                ["timeline.endOfTimeline"] = "Hết sự kiện",
                ["timeline.loading"] = "Đang tải...",
                ["timeline.loadingMore"] = "Đang tải thêm...",
                ["timeline.loadMore"] = "Tải thêm",
                ["timeline.myGroups"] = "Nhóm của tôi",
                ["timeline.noGroups"] = "Bạn chưa tham gia nhóm nào.",
                ["timeline.noGroupSelected"] = "Chưa chọn nhóm",
                ["timeline.selectGroup"] = "Chọn nhóm",
                ["timeline.selectGroupFirst"] = "Hãy chọn một nhóm để xem Timeline.",
                ["blocked.block"] = "Chặn",
                ["blocked.blocking"] = "Đang chặn...",
                ["blocked.blockUserSubtitle"] = "Nhập ID người dùng để chặn. Họ sẽ không thể nhắn tin hay tương tác với bạn.",
                ["blocked.blockUserTitle"] = "Chặn người dùng",
                ["blocked.clearSelection"] = "Hủy chọn",
                ["blocked.noResults"] = "Không tìm thấy kết quả.",
                ["blocked.searchPlaceholder"] = "Nhập ID hoặc tên để tìm...",
                ["blocked.selectedToBlock"] = "Đang chọn:",
                ["sessions.active"] = "Đang hoạt động",
                ["sessions.expires"] = "Hết hạn",
                ["sessions.logoutOthers"] = "Đăng xuất các thiết bị khác",
                ["sessions.unknownDevice"] = "Thiết bị không rõ",
                ["sessions.unknownIp"] = "IP không rõ",
                ["task.allAssignees"] = "Tất cả người được giao",
                ["task.allGroups"] = "Tất cả nhóm",
                ["task.allPriority"] = "Tất cả mức độ",
                ["task.allStatus"] = "Tất cả trạng thái",
                ["task.apply"] = "Áp dụng",
                ["task.assignedToMe"] = "Giao cho tôi",
                ["task.assignee"] = "Người thực hiện",
                ["task.creator"] = "Người tạo",
                ["task.due"] = "Hạn",
                ["task.group"] = "Nhóm",
                ["task.groupId"] = "ID Nhóm",
                ["task.loading"] = "Đang tải...",
                ["task.overdue"] = "Quá hạn",
                ["task.refresh"] = "Làm mới",
                ["task.reopen"] = "Mở lại",
                ["task.search"] = "Tìm kiếm task...",
                ["task.unassigned"] = "Chưa giao",
            },
            ["en"] = new Dictionary<string, string>
            {
                ["nav.messages"] = "Messages",
                ["nav.groups"] = "Groups",
                ["nav.search"] = "Search",
                ["nav.saved"] = "Saved",
                ["nav.friends"] = "Friends",
                ["nav.code"] = "Code",
                ["nav.ioc"] = "IOC",
                ["nav.pentest"] = "Pentest",
                ["nav.timeline"] = "Timeline",
                ["nav.tasks"] = "Tasks",
                ["nav.secrets"] = "Secrets",
                ["nav.blocked"] = "Blocked",
                ["nav.sessions"] = "Sessions",
                ["nav.settings"] = "Settings",

                ["account.profile"] = "Profile",
                ["account.logout"] = "Log out",
                ["account.language"] = "Language",
                ["account.vietnamese"] = "Tiếng Việt",
                ["account.english"] = "English",
                ["account.switchToEnglish"] = "Switch to English",
                ["account.switchToVietnamese"] = "Chuyển sang Tiếng Việt",

                ["saved.title"] = "Saved messages",
                ["saved.subtitle"] = "Bookmark important messages for quick access.",
                ["saved.all"] = "All",
                ["saved.dm"] = "DM",
                ["saved.group"] = "Group",
                ["saved.empty"] = "No saved messages yet",
                ["saved.openOriginal"] = "Open original",
                ["saved.unsave"] = "Unsave",
                ["saved.messageTime"] = "Message",
                ["saved.savedAt"] = "Saved",
                ["saved.removed"] = "Message unsaved.",
                ["saved.removeFailed"] = "Could not unsave message.",

                ["message.save"] = "Save message",
                ["message.unsave"] = "Unsave",
                ["message.saved"] = "Message saved.",
                ["message.unsaved"] = "Message unsaved.",
                ["message.saveFailed"] = "Could not update saved state.",

                ["time.today"] = "Today",
                ["time.yesterday"] = "Yesterday",
                ["time.justNow"] = "Just now",

                ["chat.emptyTitle"] = "Select a conversation",
                ["chat.emptySubtitle"] = "Choose from the list on the left or start a new conversation",
                ["chat.messagesTitle"] = "Messages",
                ["chat.searchPlaceholder"] = "Search...",
                ["chat.inputPlaceholder"] = "Type a message... Use / for commands, @ to mention members",
                ["chat.groupLabel"] = "Group",

                ["reminder.title"] = "Reminder",
                ["reminder.created"] = "Reminder created",
                ["reminder.syntax"] = "Usage: /reminder 10m reminder text",
                ["reminder.pending"] = "Pending",
                ["reminder.sent"] = "Sent",
                ["reminder.completed"] = "Completed",
                ["reminder.cancelled"] = "Cancelled",
                ["reminder.dueAt"] = "Due at",
                ["reminder.fromCommand"] = "Created from /reminder command",

                ["search.title"] = "Search",
                ["search.subtitle"] = "Search messages, users, groups, snippets, IOC, findings, tasks, and files.",
                ["search.placeholder"] = "Enter a keyword...",
                ["search.typeAll"] = "All",
                ["search.typeMessage"] = "Messages",
                ["search.typeUser"] = "Users",
                ["search.typeGroup"] = "Groups",
                ["search.typeSnippet"] = "Snippets",
                ["search.typeIoc"] = "IOC",
                ["search.typeAttachment"] = "Files",
                ["search.typeFinding"] = "Findings",
                ["search.typeTask"] = "Tasks",
                ["search.fromDate"] = "From date",
                ["search.toDate"] = "To date",
                ["search.sender"] = "Sender",
                ["search.group"] = "Group",
                ["search.directChatUser"] = "Direct chat user",
                ["search.allSenders"] = "All senders",
                ["search.allGroups"] = "All groups",
                ["search.allDirectChats"] = "All direct chats",
                ["search.severity"] = "Severity",
                ["search.allSeverities"] = "All severities",
                ["search.noResults"] = "No results found",
                ["search.open"] = "Open",
                ["search.openMessage"] = "Open message",
                ["search.openFile"] = "Open file",
                ["search.clearFilters"] = "Clear filters",
                ["search.searching"] = "Searching...",
                ["search.loadMore"] = "Load more",
                ["search.dmWith"] = "DM with {0}",
                ["search.groupContext"] = "Group: {0}",
                ["search.senderContext"] = "Sender: {0}",
                ["search.messageId"] = "Message #{0}",

                ["pentest.trackerTitle"] = "Pentest Finding Tracker",
                ["pentest.findingTracker"] = "Pentest Finding Tracker",
                ["pentest.trackerSubtitle"] = "Manage vulnerabilities by group, endpoint, payload, and remediation status.",
                ["pentest.totalFindings"] = "Total Findings",
                ["pentest.criticalHigh"] = "Critical/High",
                ["pentest.openFindings"] = "Open",
                ["pentest.closedMitigated"] = "Mitigated/Closed",
                ["pentest.findingDetail"] = "Finding Detail",
                ["pentest.newFinding"] = "New Finding",
                ["pentest.editFinding"] = "Edit Finding",
                ["pentest.affectedTarget"] = "Affected target",
                ["pentest.affectedEndpoint"] = "Affected endpoint",
                ["pentest.httpMethod"] = "HTTP method",
                ["pentest.payload"] = "Payload",
                ["pentest.technicalProof"] = "Technical Proof",
                ["pentest.overview"] = "Overview",
                ["pentest.fix"] = "Fix",
                ["pentest.noContent"] = "No content",
                ["pentest.openInTracker"] = "Open in Finding Tracker",
                ["pentest.createdFromVuln"] = "Created from /vuln command",
                ["pentest.createdSuccess"] = "Created finding.",
                ["pentest.updatedSuccess"] = "Updated finding.",
                ["pentest.deletedSuccess"] = "Deleted finding.",
                ["pentest.vulnCreatedSuccess"] = "Created Finding from /vuln",

                ["secrets.title"] = "One-time Secret",
                ["secrets.subtitle"] = "Share passwords, API keys, or sensitive notes with a link that can be opened only once.",
                ["secrets.refresh"] = "Refresh",
                ["secrets.createTitle"] = "Create secret",
                ["secrets.secretLabel"] = "Secret",
                ["secrets.expiresLabel"] = "Expires",
                ["secrets.expires5m"] = "5 minutes",
                ["secrets.expires1h"] = "1 hour",
                ["secrets.expires1d"] = "1 day",
                ["secrets.createButton"] = "Create secret",
                ["secrets.createdList"] = "Created secrets",
                ["secrets.createdAt"] = "Created at",
                ["secrets.expiresAt"] = "Expires at",
                ["secrets.viewedAt"] = "Viewed at",
                ["secrets.status"] = "Status",
                ["secrets.viewer"] = "Viewer",
                ["secrets.revoke"] = "Revoke",
                ["secrets.empty"] = "No secrets yet.",
                ["secrets.shareOnce"] = "This link is shown once. Copy it now.",
                ["secrets.shareLink"] = "Share link",
                ["secrets.copyLink"] = "Copy link",
                ["secrets.created"] = "Secret created",
                ["secrets.createFailed"] = "Could not create secret",
                ["secrets.copyDone"] = "Link copied",
                ["secrets.revokeDone"] = "Secret revoked",
                ["secrets.revokeFailed"] = "Could not revoke secret",
                ["secrets.externalViewer"] = "External viewer",
                ["secrets.statusActive"] = "Active",
                ["secrets.statusViewed"] = "Viewed",
                ["secrets.statusExpired"] = "Expired",
                ["secrets.statusRevoked"] = "Revoked",

                ["openSecret.title"] = "One-time Secret",
                ["openSecret.openedNotice"] = "Secret opened. This link cannot be viewed again.",
                ["openSecret.copySecret"] = "Copy secret",
                ["openSecret.warning"] = "The secret is shown only once. Open it only when you are ready to save the content.",
                ["openSecret.openButton"] = "Open secret",
                ["openSecret.expiredOrViewed"] = "Secret expired or already viewed",
                ["friends.title"] = "Friends",
                ["friends.searchPlaceholder"] = "Enter name, username, email...",
                ["friends.noResults"] = "No users found matching \"{0}\".",
                ["friends.sendRequest"] = "Send friend request",
                ["friends.tabFriends"] = "Friends",
                ["friends.tabReceived"] = "Received requests",
                ["friends.tabSent"] = "Sent requests",
                ["friends.noFriends"] = "No friends yet.",
                ["friends.message"] = "Message",
                ["friends.remove"] = "Remove friend",
                ["friends.noReceived"] = "No pending requests.",
                ["friends.sender"] = "Sender",
                ["friends.time"] = "Time",
                ["friends.noSent"] = "No sent requests.",
                ["friends.receiver"] = "Receiver",
                ["friends.searchNew"] = "Find new friends",
                ["snippets.title"] = "Code Snippets",
                ["snippets.subtitle"] = "Save, search, and share internal code snippets.",
                ["snippets.createBtn"] = "Create new snippet",
                ["snippets.searchPlaceholder"] = "Search by title, content, or language...",
                ["snippets.allLanguages"] = "All languages",
                ["snippets.empty"] = "You don't have any snippets. Create your first snippet to save frequently used code.",
                ["snippets.noFilterResults"] = "No snippets found matching current filters.",
                ["snippets.noTitle"] = "No title",
                ["snippets.revoked"] = "Revoked",
                ["snippets.expired"] = "Expired",
                ["snippets.noExpiry"] = "No expiration",
                ["snippets.views"] = "{0} views",
                ["snippets.copyLink"] = "Copy share link",
                ["snippets.copyCode"] = "Copy code",
                ["snippets.edit"] = "Edit snippet",
                ["snippets.viewFull"] = "View full",
                ["snippets.fullscreen"] = "Fullscreen",
                ["snippets.restoreLink"] = "Restore share link",
                ["snippets.revokeLink"] = "Revoke share link",
                ["snippets.delete"] = "Delete snippet",
                ["snippets.createTitleModal"] = "Create New Code Snippet",
                ["snippets.createSubtitleModal"] = "Save snippet to your internal code repository.",
                ["snippets.titleLabel"] = "Title (optional)",
                ["snippets.titleHelper"] = "If left blank, a title will be generated.",
                ["snippets.languageLabel"] = "Language",
                ["snippets.codeLabel"] = "Code *",
                ["snippets.codeHelper"] = "You can paste raw code or markdown block ```python ... ```, the system will clean it up.",
                ["snippets.expiryLabel"] = "Share link expiration",
                ["snippets.cancel"] = "Cancel",
                ["snippets.create"] = "Create",
                ["snippets.editTitleModal"] = "Edit Code Snippet",
                ["snippets.editSubtitleModal"] = "Edit title, language, and code. The current share link will be preserved.",
                ["snippets.saveChanges"] = "Save changes",
                ["snippets.close"] = "Close",
                ["ioc.title"] = "IOC Center",
                ["ioc.subtitle"] = "Store, search, and share Indicators of Compromise.",
                ["ioc.searchPlaceholder"] = "Search by value or note...",
                ["ioc.addIoc"] = "Add IOC",
                ["ioc.type"] = "Type",
                ["ioc.allTypes"] = "All types",
                ["ioc.severity"] = "Severity",
                ["ioc.allSeverities"] = "All severities",
                ["ioc.empty"] = "You have no saved IOCs.",
                ["ioc.noFilterResults"] = "No IOCs match the filters.",
                ["ioc.value"] = "Value",
                ["ioc.note"] = "Note",
                ["ioc.createdAt"] = "Created at",
                ["ioc.actions"] = "Actions",
                ["ioc.edit"] = "Edit IOC",
                ["ioc.delete"] = "Delete IOC",
                ["ioc.cancel"] = "Cancel",
                ["ioc.save"] = "Save",
                ["ioc.group"] = "Group",
                ["ioc.severityLow"] = "Low",
                ["ioc.severityMedium"] = "Medium",
                ["ioc.severityHigh"] = "High",
                ["ioc.severityCritical"] = "Critical",
                ["pentest.title"] = "Pentest",
                ["timeline.title"] = "Threat Timeline",
                ["timeline.subtitle"] = "Track and analyze security events in real time.",
                ["timeline.addEvent"] = "Add event",
                ["timeline.empty"] = "No events yet. Add the first event.",
                ["timeline.eventTitle"] = "Event title",
                ["timeline.eventTime"] = "Time",
                ["timeline.eventDescription"] = "Description / Details",
                ["timeline.cancel"] = "Cancel",
                ["timeline.save"] = "Save",
                ["timeline.delete"] = "Delete event",
                ["timeline.edit"] = "Edit event",
                ["timeline.searchPlaceholder"] = "Search events...",
                ["task.title"] = "Task Center",
                ["task.subtitle"] = "Manage tasks and track progress.",
                ["task.addTask"] = "Add Task",
                ["task.empty"] = "No tasks yet.",
                ["task.todo"] = "To Do",
                ["task.inProgress"] = "In Progress",
                ["task.done"] = "Done",
                ["task.taskName"] = "Task name",
                ["task.assignee"] = "Assignee",
                ["task.dueDate"] = "Due date",
                ["task.priority"] = "Priority",
                ["task.save"] = "Save task",
                ["task.cancel"] = "Cancel",
                ["task.edit"] = "Edit task",
                ["task.delete"] = "Delete task",
                ["blocked.title"] = "Blocked Users",
                ["blocked.subtitle"] = "Manage the list of users you have blocked.",
                ["blocked.empty"] = "You haven't blocked anyone.",
                ["blocked.unblock"] = "Unblock",
                ["blocked.name"] = "Username",
                ["blocked.blockedAt"] = "Blocked at",
                ["sessions.title"] = "Active Sessions",
                ["sessions.subtitle"] = "Manage devices currently logged into your account.",
                ["sessions.current"] = "Current session",
                ["sessions.revoke"] = "Log out",
                ["sessions.revokeAll"] = "Log out all other sessions",
                ["sessions.browser"] = "Browser",
                ["sessions.ip"] = "IP Address",
                ["sessions.lastAccess"] = "Last access",
                ["sessions.os"] = "OS",
                ["pentest.cancel"] = "Cancel",
                ["pentest.close"] = "Close",
                ["pentest.create"] = "Create",
                ["pentest.created"] = "Created",
                ["pentest.delete"] = "Delete",
                ["pentest.description"] = "Description",
                ["pentest.detailEmpty"] = "No details",
                ["pentest.detailTitle"] = "Finding detail",
                ["pentest.edit"] = "Edit",
                ["pentest.empty"] = "No findings found.",
                ["pentest.endpoint"] = "Endpoint",
                ["pentest.filter"] = "Filter",
                ["pentest.findings"] = "Findings",
                ["pentest.fix"] = "Remediation",
                ["pentest.group"] = "Group",
                ["pentest.groupId"] = "Group ID",
                ["pentest.loading"] = "Loading...",
                ["pentest.loadMore"] = "Load more",
                ["pentest.method"] = "Method",
                ["pentest.open"] = "Open",
                ["pentest.openGroup"] = "Open Group",
                ["pentest.overview"] = "Overview",
                ["pentest.payload"] = "Payload",
                ["pentest.poc"] = "PoC",
                ["pentest.proof"] = "Proof",
                ["pentest.refresh"] = "Refresh",
                ["pentest.remediation"] = "Remediation",
                ["pentest.results"] = "results",
                ["pentest.save"] = "Save",
                ["pentest.search"] = "Search...",
                ["pentest.severity"] = "Severity",
                ["pentest.status"] = "Status",
                ["pentest.subtitle"] = "Manage vulnerabilities by group, endpoint, payload, and status.",
                ["pentest.target"] = "Target",
                ["pentest.titleField"] = "Title",
                ["pentest.total"] = "Total",
                ["pentest.updated"] = "Updated",
                ["pentest.view"] = "View",
                ["timeline.all"] = "All",
                ["timeline.download"] = "Download",
                ["timeline.emptyDesc"] = "No activity recorded yet.",
                ["timeline.endOfTimeline"] = "End of timeline",
                ["timeline.loading"] = "Loading...",
                ["timeline.loadingMore"] = "Loading more...",
                ["timeline.loadMore"] = "Load more",
                ["timeline.myGroups"] = "My Groups",
                ["timeline.noGroups"] = "You haven't joined any groups.",
                ["timeline.noGroupSelected"] = "No group selected",
                ["timeline.selectGroup"] = "Select a group",
                ["timeline.selectGroupFirst"] = "Please select a group to view its Timeline.",
                ["blocked.block"] = "Block",
                ["blocked.blocking"] = "Blocking...",
                ["blocked.blockUserSubtitle"] = "Enter user ID to block. They won't be able to message or interact with you.",
                ["blocked.blockUserTitle"] = "Block User",
                ["blocked.clearSelection"] = "Clear selection",
                ["blocked.noResults"] = "No results found.",
                ["blocked.searchPlaceholder"] = "Search by ID or name...",
                ["blocked.selectedToBlock"] = "Selected to block:",
                ["sessions.active"] = "Active",
                ["sessions.expires"] = "Expires",
                ["sessions.logoutOthers"] = "Log out other devices",
                ["sessions.unknownDevice"] = "Unknown device",
                ["sessions.unknownIp"] = "Unknown IP",
                ["task.allAssignees"] = "All assignees",
                ["task.allGroups"] = "All groups",
                ["task.allPriority"] = "All Priorities",
                ["task.allStatus"] = "All Statuses",
                ["task.apply"] = "Apply",
                ["task.assignedToMe"] = "Assigned to me",
                ["task.assignee"] = "Assignee",
                ["task.creator"] = "Creator",
                ["task.due"] = "Due",
                ["task.group"] = "Group",
                ["task.groupId"] = "Group ID",
                ["task.loading"] = "Loading...",
                ["task.overdue"] = "Overdue",
                ["task.refresh"] = "Refresh",
                ["task.reopen"] = "Reopen",
                ["task.search"] = "Search tasks...",
                ["task.unassigned"] = "Unassigned",
            }
        };
}

