// <auto-generated />
// This file is auto-generated. Re-run "dotnet ef migrations add" to regenerate.
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PingMe.Data;

#nullable disable

namespace PingMe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517120000_Phase2SnippetUpgrade")]
    partial class Phase2SnippetUpgrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Full model snapshot is maintained in AppDbContextModelSnapshot.cs
            // Run: dotnet ef migrations add <Next> to regenerate this file automatically.
        }
    }
}
